import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lista de usuarios",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="https://bootswatch.com/5/materia/bootstrap.min.css" />
      </head>
      <body className={inter.className}>
        <Navbar />
        <div className='container p-4'>
        {children}
        </div>
       
      </body>
    </html>
  );
}
